# PUBLICATION META INFO
# —————————————————————

title:                  "Specific Threats to Human Rights Protection from the Digital Reality"
subtitle:               "International Responses and Recommendations to Core Threats from the Digitalised World"
authors:                "Tiina Pajuste (Ed.)"
year:                   2022
date_publication:       October 2022
# date_submission:
# date_last_updated:

keywords:               human rights, digital reality, digital threats, policy proposals, international action, human rights protection

abstract:               "Digital technologies come with both widespread benefits and potential threats to people and communities across the globe. It is important to be aware of the threats in order to fully harness the positive potential of digital technologies. This report hopes to contribute to this goal. It is a compilation of contributions from twenty-two researchers from the Global Digital Human Rights Network. The report highlights some core problems that can arise in the digital realm. The report is divided into five parts: (a) overarching issues that impact human rights in general, (b) threats that are connected to technology/technological advancements, (c) threats connected to disinformation, (d) threats connected to privacy and freedom of expression, and (e) threats in relation to vulnerable groups.\n
 
The amplitude of different threats makes it essential that these technologies are reined in by effective regulation based on international human rights law and standards. The initiatives taken on both regional and global levels are noted in this report in relation to each threat that is addressed. Each report section concludes with recommendations for policies and activities that are aimed at minimising threats to human rights protection from the digital environment."

# <h3>Authors</h3>\n
# Wolfgang Benedek, Alex Fischer, Gregor Fischer-Lessiak, Vivienne Gold, Matthias C. Kettemann, Birgit Schippers, Mart Susi, Jukka Viljanen"

cite_as:               "Tiina Pajuste (ed.), Specific Threats to Human Rights Protection from the Digital Reality (Tallinn: Tallinn University, 2022) "

pdf_url:                https://graphite.page/GDHRNet-threats-to-human-rights-protection/assets/documents/GDHRNet-ThreatsReport-EditedVolume.pdf
# doi:                    10.21241/ssoar.78580
# isbn:                   978-989-746-128-6
contact_email:          t.pajuste@gmail.com

short_url:              https://graphite.page/GDHRNet-threats-to-human-rights-protection
social_image_url:       https://graphite.page/GDHRNet-threats-to-human-rights-protection/assets/images/social.png
lang:                   en


# PUBLICATION STYLE
# —————————————————————
styles:                 theme/styles/GDHRNet.css
background_url:         theme/images/bg.png



# DISCLAIMER
# —————————————————————
# data_usage:
# disclaimer:
# terms_of_use:
licence:                CC BY SA 4.0

# Author info is shown in footer bar and on the right, if no logo is provided.
author_info:            A Global Digital Human Rights Network (GDHRNet) study
logo_url:               theme/images/Logo_GDHRNet_horizontal.svg


# SETTINGS
# —————————————————————

author_info_sticky:     true
no_journal:             false
matomo_tracking:        true
matomo_url:             "https://piwik.wunderjewel.de/"
matomo_siteId:          "4"
load_confetti:          false


# PUBLISHER INFO
# thanks for mentioning graphite
# —————————————————————

brand:                  graphite – Enhanced publications for a digital environment
brand_url:              https://www.impactdistillery.com/graphite
brand_logo:             theme/images/graphite.svg

# Infos in expandable header
imprint:                "This is a publication from the Global Digital Human Rights Network (GDHRNet), edited by Matthias C. Kettemann.\n\n
The publication is based upon work from COST Action GDHRNet – CA19143, supported by COST (European Cooperation in Science and Technology"

further_publications:
   - label: "#1: Viral Information"
     url: https://graphite.page/GDHRNet-WP1
   - label: "#2: Covid-19 “Vaccine Passport”"
     url: https://graphite.page/GDHRNet-WP2
   - label: "#3: Can Platforms Cancel Politicians?"
     url: https://graphite.page/GDHRNet-WP3
   - label: "#4: Governing Information Flows During War?"
     url: https://graphite.page/GDHRNet-WP4

further_links:
   - label: Global Digital Human Rights Network
     url: https://gdhrnet.eu
   - label: COST Action GDHRNet – CA19143
     url: https://www.cost.eu/actions/CA19143


# TABS
# —————————————————————

:---------------------------------------------------:
tabs:
  - title: "Study"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
  - title: "Recommendations"
    slug: summary
    md_container: section
  - title: "Contributors"
    slug: contributors
    md_container: section
  - title: "About the study"
    slug: series
    md_container: section
