powered_by:         runs on
abstract:           Abstract
download:           PDF
share:              Share
date_publication:   Published
keywords:           Keywords
cite_as:            Recommended citation
quote_open:         "&ldquo;"
quote_close:        "&rdquo;"
downloadData:       Download data
toc:                Contents
toc_long:           Contents
questions:          Questions?
write_mail:         Feel free to contact
read_on:            Read paper
cited_source:       Quoted source
authors:            Authors
visit_website:      Visit website
header_articles:    All working papers
header_more:        More on GDHRNet
