# PUBLICATION META INFO
# —————————————————————

title:                  "Do the New European Rules on Digital Services Effectively Ensure Human Rights on Platforms? "
subtitle:               "Guidelines for Companies"
authors:                "Martin Müller, Felicitas Rachinger, Meryem Vural & Matthias C. Kettemann"
year:                   2024
date_publication:       September 2024
# date_submission:
# date_last_updated:

keywords:               Digital Services Act, Digital Services Coordinator, human rights online, EU, digital governance

abstract:               "This study is a key output from the  GDHRNet (Global Digital Human Rights Network), which is dedicated to the investigation of theoretical and practical challenges of the protection of human rights in the digital context.\n

  It is presented as part one of two outlining key outputs from common research efforts, and  aims to establish standards and recommendations for online intermediaries to assess their compliance with human rights obligations. The research is based on a questionnaire distributed to GDHRNet members, with responses from nine participants representing both EU and non-EU countries.\n

  The findings underscore the centrality of the Digital Services Act (DSA) in European platform regulation, alongside other relevant EU legislative acts such as the GDPR and the Audiovisual Media Services Directive. The study highlights the influence of EU legislation on national laws, including in non-EU states, and the pervasive “Brussels Effect” shaping legal framework. The study briefly explores the DSA’s provisions, including liability exemptions, obligations related to terms of service, transparency requirements, and regulations on algorithmic recommender systems. It provides an overview of the current regulatory landscape, emphasizing the importance of harmonizing platform regulations with human rights obligations across both EU and non-EU countries."

cite_as:                "Martin Müller, Felicitas Rachinger, Meryem Vural & Matthias C. Kettemann, Do the New European Rules on Digital Services Effectively Ensure Human Rights on Platforms. Guidelines for Companies. (Hamburg: Verlag Hans-Bredow-Institut, 2024)"

pdf_url:                https://graphite.page/dsa-guidelines/assets/documents/GDHRNet-DSA-Guidelines.pdf
# doi:                    10.21241/ssoar.78580
# isbn:                   978-989-746-128-6
contact_email:          m.kettemann@leibniz-hbi.de

short_url:              https://graphite.page/dsa-guidelines
social_image_url:       https://graphite.page/dsa-guidelines/assets/images/social.png
lang:                   en


# PUBLICATION STYLE
# —————————————————————
styles:                 theme/styles/GDHRNet.css
background_url:         theme/images/bg.png



# DISCLAIMER
# —————————————————————
# data_usage:
# disclaimer:
# terms_of_use:
licence:                CC BY SA 4.0

# Author info is shown in footer bar and on the right, if no logo is provided.
author_info:            A Global Digital Human Rights Network (GDHRNet) milestone output
logo_url:               theme/images/Logo_GDHRNet_horizontal.svg


# SETTINGS
# —————————————————————

author_info_sticky:     true
no_journal:             false
matomo_tracking:        true
matomo_url:             "https://piwik.wunderjewel.de/"
matomo_siteId:          "4"
load_confetti:          false


# PUBLISHER INFO
# thanks for mentioning graphite
# —————————————————————

brand:                  graphite – Enhanced publications for a digital environment
brand_url:              https://www.impactdistillery.com/graphite
brand_logo:             theme/images/graphite.svg

# Infos in expandable header
imprint:                "This is a publication from the Global Digital Human Rights Network (GDHRNet) working paper series, edited by by Mart Susi and Matthias C. Kettemann.\n\n
                        The publication is based upon work from COST Action GDHRNet – CA19143, supported by COST (European Cooperation in Science and Technology"

further_publications:
   - label: "#1: Viral Information"
     url: https://graphite.page/GDHRNet-WP1
   - label: "#2: Covid-19 “Vaccine Passport”"
     url: https://graphite.page/GDHRNet-WP2
   - label: "#3: Can Platforms Cancel Politicians?"
     url: https://graphite.page/GDHRNet-WP3
   - label: "#4: Governing Information Flows During War?"
     url: https://graphite.page/GDHRNet-WP4

further_links:
   - label: "Part #2 of the study: Assessment Model for States"
     url: https://graphite.page/DSA-assessment-model
   - label: Global Digital Human Rights Network
     url: https://gdhrnet.eu
   - label: COST Action GDHRNet – CA19143
     url: https://www.cost.eu/actions/CA19143


# TABS
# —————————————————————

:---------------------------------------------------:
tabs:
  - title: "Study"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
  - title: "Contributions"
    slug: contributions
    md_container: article
  - title: "About the series"
    slug: series
    md_container: section
