# PUBLICATION META INFO
# —————————————————————

title:                  "Do the New European Rules on Digital Services Effectively Ensure Human Rights on Platforms? "
subtitle:               "Assessment Model for States"
authors:                "Martin Müller, Felicitas Rachinger, Meryem Vural & Matthias C. Kettemann"
year:                   2024
date_publication:       September 2024
# date_submission:
# date_last_updated:

keywords:               Digital Services Act, Digital Services Coordinator, human rights online, EU, digital governance

abstract:               "This study is a key output from the  GDHRNet (Global Digital Human Rights Network), which is dedicated to the investigation of theoretical and practical challenges of the protection of human rights in the digital context. The study aims to develop an assessment model to evaluate the compliance of online companies with human rights protection obligations. The research utilized a questionnaire focused on national platform oversight structures, sent to GDHRNet members, with responses from nine participants, seven from EU member states and two from non-EU states.\n

  The study's findings revealed that most participating states have appointed a Digital Services Coordinator (DSC) as required under the Digital Services Act (DSA), typically selecting existing telecommunications or media authorities for this role. While most DSCs are reported to be adequately equipped, staffing and financing issues remain. DSCs generally have sufficient authority to request data from service providers, and national legislation aligns closely with DSA requirements, particularly regarding sanctions for non-compliance."

cite_as:                "Martin Müller, Felicitas Rachinger, Meryem Vural & Matthias C. Kettemann, Do the New European Rules on Digital Services Effectively Ensure Human Rights on Platforms. Assessment Model for States. (Hamburg: Verlag Hans-Bredow-Institut, 2024)"

pdf_url:                https://graphite.page/GDHRNet-WP2/assets/documents/GDHRNet-Working_Paper-4.pdf
# doi:                    10.21241/ssoar.78580
# isbn:                   978-989-746-128-6
contact_email:          m.kettemann@leibniz-hbi.de

short_url:              https://graphite.page/DSA-assessment-model
social_image_url:       https://graphite.page/DSA-assessment-model/assets/images/social.png
lang:                   en


# PUBLICATION STYLE
# —————————————————————
styles:                 theme/styles/GDHRNet.css
background_url:         theme/images/bg.png



# DISCLAIMER
# —————————————————————
# data_usage:
# disclaimer:
# terms_of_use:
licence:                CC BY SA 4.0

# Author info is shown in footer bar and on the right, if no logo is provided.
author_info:            A Global Digital Human Rights Network (GDHRNet) milestone output
logo_url:               theme/images/Logo_GDHRNet_horizontal.svg


# SETTINGS
# —————————————————————

author_info_sticky:     true
no_journal:             false
matomo_tracking:        true
matomo_url:             "https://piwik.wunderjewel.de/"
matomo_siteId:          "4"
load_confetti:          false


# PUBLISHER INFO
# thanks for mentioning graphite
# —————————————————————

brand:                  graphite – Enhanced publications for a digital environment
brand_url:              https://www.impactdistillery.com/graphite
brand_logo:             theme/images/graphite.svg

# Infos in expandable header
imprint:                "This is a publication from the Global Digital Human Rights Network (GDHRNet) working paper series, edited by by Mart Susi and Matthias C. Kettemann.\n\n
                        The publication is based upon work from COST Action GDHRNet – CA19143, supported by COST (European Cooperation in Science and Technology"

further_publications:
   - label: "#1: Viral Information"
     url: https://graphite.page/GDHRNet-WP1
   - label: "#2: Covid-19 “Vaccine Passport”"
     url: https://graphite.page/GDHRNet-WP2
   - label: "#3: Can Platforms Cancel Politicians?"
     url: https://graphite.page/GDHRNet-WP3
   - label: "#4: Governing Information Flows During War?"
     url: https://graphite.page/GDHRNet-WP4

further_links:
   - label: "Part #1 of the study: Guidelines for Companies"
     url: https://graphite.page/dsa-guidelines
   - label: Global Digital Human Rights Network
     url: https://gdhrnet.eu
   - label: COST Action GDHRNet – CA19143
     url: https://www.cost.eu/actions/CA19143


# TABS
# —————————————————————

:---------------------------------------------------:
tabs:
  - title: "Study"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
  - title: "Contributions"
    slug: contributions
    md_container: article
  - title: "About the series"
    slug: series
    md_container: section
