# PUBLICATION META INFO
# —————————————————————

title:                  "Can Platforms Cancel Politicians?"
subtitle:               "How States and Platforms Deal with Private Power over Political Actors: an Exploratory Study of 15 Countries"
authors:                "Martin Fertmann and Matthias C. Kettemann (Eds.)"
year:                   2021
date_publication:       July 2021
# date_submission:
# date_last_updated:

keywords:               Platform Governance, Public Actors, Political Candidates, Newsworthiness Exemption, National Contexts
abstract:               "In January 2021, a great “deplatforming” took place: Numerous internet platforms suspended the accounts of Donald Trump and his supporters. Private power over public speech is often contested, but the conflicts are magnified when this power is asserted over parties, political candidates and office holders that function as focal points for public debates. While most platforms’ terms of use and enforcement systems are global, opinions relating to any preferential treatment of speech by well-known political figures and office holders vary across national political and legal contexts.\n\n

This study examines the interplay between these national conceptions and global private ordering systems by synthesizing answers to nine questions submitted by more than 30 researchers from 15 countries within the GDHR Network. It provides a first overview of how societies and governments conceive of and react to private power over political actors.\n\n

**“All human beings are born free and equal in dignity and rights.”**<br>
The illustration above shows the first sentence of Article 1 of the Universal Declaration of Human Rights (1948) rendered in machine-readable barcode."

cite_as:               "Martin Fertmann and Matthias C. Kettemann (eds.), Can Platforms Cancel Politicians? How States and Platforms Deal with Private Power over Political Actors: an Exploratory Study of 15 Countries (Hamburg: Verlag Hans-Bredow-Institut, 2021), GDHRNet Working Paper #3"

pdf_url:                https://graphite.page/GDHRNet-WP3/assets/documents/GDHRNet-Working_Paper-#3.pdf
# doi:                    10.5281/zenodo.4291999
# isbn:                   978-989-746-128-6
contact_email:          m.kettemann@leibniz-hbi.de

short_url:              https://graphite.page/GDHRNet-WP3
social_image_url:       https://graphite.page/GDHRNet-WP3/assets/images/social.png
lang:                   en


# PUBLICATION STYLE
# —————————————————————
styles:                 theme/styles/GDHRNet.css
background_url:         theme/images/bg.png



# DISCLAIMER
# —————————————————————
# data_usage:
# disclaimer:
# terms_of_use:
licence:                CC BY SA 4.0

# Author info is shown in footer bar and on the right, if no logo is provided.
author_info:            A Global Digital Human Rights Network (GDHRNet) working paper
logo_url:               theme/images/Logo_GDHRNet_horizontal.svg


# SETTINGS
# —————————————————————

author_info_sticky:     true
no_journal:             false
matomo_tracking:        true
matomo_url:             "https://piwik.wunderjewel.de/"
matomo_siteId:          "4"
load_confetti:          false


# PUBLISHER INFO
# thanks for mentioning graphite
# —————————————————————

brand:                  graphite – Enhanced publications for a digital environment
brand_url:              https://www.impactdistillery.com/graphite
brand_logo:             theme/images/graphite.svg

# Infos in expandable header
imprint:                "This is a publication from the Global Digital Human Rights Network (GDHRNet) working paper series, edited by Matthias C. Kettemann and Martin Fertmann.\n\n
The publication is based upon work from COST Action GDHRNet – CA19143, supported by COST (European Cooperation in Science and Technology"

further_publications:
   - label: "#1: Viral Information"
     url: https://graphite.page/GDHRNet-WP1
   - label: "#2: Viral Information"
     url: https://graphite.page/GDHRNet-WP1

further_links:
   - label: Global Digital Human Rights Network
     url: https://gdhrnet.eu
   - label: COST Action GDHRNet – CA19143
     url: https://www.cost.eu/actions/CA19143


# TABS
# —————————————————————

:---------------------------------------------------:
tabs:
  - title: "Study"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
  - title: "National Contributions"
    ref: "/contributions"
    slug: contributions
    md_container: article
  - title: "Executive Summary"
    ref: "/summary"
    slug: summary
    md_container: section
  - title: "About the series"
    ref: "/series/"
    slug: series
    md_container: section
